export const header = [
  { key: "name", label: "Name" },
  { key: "company", label: "Company" },
  { key: "job_title", label: "Job Title" },
  { key: "location", label: "Location" },
  { key: "score", label: "Score" },
  { key: "status", label: "Status" },
];
export const rows = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    company: "Tech Innovations Inc.",
    job_title: "CEO",
    status: "Hot",
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    company: "Global Solutions Ltd.",
    job_title: "Sales Agent",
    status: "Warm",
  },
  {
    id: 3,
    name: "Carol Davis",
    email: "carol.davis@example.com",
    company: "Marketing Gurus",
    job_title: "Sales Agent",
    status: "Luke Warm",
  },
  {
    id: 4,
    name: "David Lee",
    email: "david.lee@example.com",
    company: "Finance Experts Co.",
    job_title: "CEO",
    status: "Cold",
  },
  {
    id: 5,
    name: "Eva Chen",
    email: "eva.chen@example.com",
    company: "Creative Solutions",
    job_title: "Sales Agent",
    status: "Hot",
  },
  {
    id: 6,
    name: "Frank Wilson",
    email: "frank.wilson@example.com",
    company: "Tech Innovations Inc.",
    job_title: "Sales Agent",
    status: "Warm",
  },
  {
    id: 7,
    name: "Grace Kim",
    email: "grace.kim@example.com",
    company: "Global Solutions Ltd.",
    job_title: "CEO",
    status: "Hot",
  },
  {
    id: 8,
    name: "Henry Taylor",
    email: "henry.taylor@example.com",
    company: "Marketing Gurus",
    job_title: "Sales Agent",
    status: "Luke Warm",
  },
  {
    id: 9,
    name: "Isabella Martinez",
    email: "isabella.martinez@example.com",
    company: "Finance Experts Co.",
    job_title: "CEO",
    status: "Cold",
  },
  {
    id: 10,
    name: "Jack Brown",
    email: "jack.brown@example.com",
    company: "Creative Solutions",
    job_title: "Sales Agent",
    status: "Hot",
  },
  {
    id: 11,
    name: "Katherine White",
    email: "katherine.white@example.com",
    company: "Tech Innovations Inc.",
    job_title: "Sales Agent",
    status: "Warm",
  },
  {
    id: 12,
    name: "Liam Anderson",
    email: "liam.anderson@example.com",
    company: "Global Solutions Ltd.",
    job_title: "CEO",
    status: "Hot",
  },
  {
    id: 13,
    name: "Mia Lewis",
    email: "mia.lewis@example.com",
    company: "Marketing Gurus",
    job_title: "Sales Agent",
    status: "Luke Warm",
  },
  {
    id: 14,
    name: "Nathan Young",
    email: "nathan.young@example.com",
    company: "Finance Experts Co.",
    job_title: "CEO",
    status: "Cold",
  },
  {
    id: 15,
    name: "Olivia Hall",
    email: "olivia.hall@example.com",
    company: "Creative Solutions",
    job_title: "Sales Agent",
    status: "Hot",
  },
  {
    id: 16,
    name: "Paul King",
    email: "paul.king@example.com",
    company: "Tech Innovations Inc.",
    job_title: "Sales Agent",
    status: "Warm",
  },
  {
    id: 17,
    name: "Quinn Wright",
    email: "quinn.wright@example.com",
    company: "Global Solutions Ltd.",
    job_title: "CEO",
    status: "Hot",
  },
  {
    id: 18,
    name: "Rita Scott",
    email: "rita.scott@example.com",
    company: "Marketing Gurus",
    job_title: "Sales Agent",
    status: "Luke Warm",
  },
  {
    id: 19,
    name: "Sam Harris",
    email: "sam.harris@example.com",
    company: "Finance Experts Co.",
    job_title: "CEO",
    status: "Cold",
  },
  {
    id: 20,
    name: "Tina Clark",
    email: "tina.clark@example.com",
    company: "Creative Solutions",
    job_title: "Sales Agent",
    status: "Hot",
  },
  {
    id: 21,
    name: "Ulysses Rodriguez",
    email: "ulysses.rodriguez@example.com",
    company: "Tech Innovations Inc.",
    job_title: "Sales Agent",
    status: "Warm",
  },
  {
    id: 22,
    name: "Victoria Green",
    email: "victoria.green@example.com",
    company: "Global Solutions Ltd.",
    job_title: "CEO",
    status: "Hot",
  },
  {
    id: 23,
    name: "William Lee",
    email: "william.lee@example.com",
    company: "Marketing Gurus",
    job_title: "Sales Agent",
    status: "Luke Warm",
  },
  {
    id: 24,
    name: "Xena Lopez",
    email: "xena.lopez@example.com",
    company: "Finance Experts Co.",
    job_title: "CEO",
    status: "Cold",
  },
  {
    id: 25,
    name: "Yara Kim",
    email: "yara.kim@example.com",
    company: "Creative Solutions",
    job_title: "Sales Agent",
    status: "Hot",
  },
  {
    id: 26,
    name: "Paul King",
    email: "paul.king@example.com",
    company: "Tech Innovations Inc.",
    job_title: "Sales Agent",
    status: "Warm",
  },
  {
    id: 27,
    name: "Quinn Wright",
    email: "quinn.wright@example.com",
    company: "Global Solutions Ltd.",
    job_title: "CEO",
    status: "Hot",
  },
  {
    id: 28,
    name: "Rita Scott",
    email: "rita.scott@example.com",
    company: "Marketing Gurus",
    job_title: "Sales Agent",
    status: "Luke Warm",
  },
  {
    id: 29,
    name: "Sam Harris",
    email: "sam.harris@example.com",
    company: "Finance Experts Co.",
    job_title: "CEO",
    status: "Cold",
  },
  {
    id: 30,
    name: "Tina Clark",
    email: "tina.clark@example.com",
    company: "Creative Solutions",
    job_title: "Sales Agent",
    status: "Hot",
  },
  {
    id: 31,
    name: "Ulysses Rodriguez",
    email: "ulysses.rodriguez@example.com",
    company: "Tech Innovations Inc.",
    job_title: "Sales Agent",
    status: "Warm",
  },
  {
    id: 32,
    name: "Victoria Green",
    email: "victoria.green@example.com",
    company: "Global Solutions Ltd.",
    job_title: "CEO",
    status: "Hot",
  },
];
export const tabs = ["Meetings", "Activity Logs", "Insights"];

export const engagementHistory = [
  {
    id: 1,
    text: "Meeting ‘Sync with Analese’ set up by Jonathon Johns",
    date: "April 26, 2024 at 08.30AM",
  },
  {
    id: 2,
    text: "Lead information updated by Jonathon Johns",
    date: "March 12, 2024 at 10.30AM",
  },
  {
    id: 3,
    text: "Follow-up mail sent by Analese Jonathon",
    date: "February 5, 2024 at 09.32AM",
  },
  {
    id: 4,
    text: "Meeting declined by Analese Jonathon",
    date: "January 6, 2024 at 14.30PM",
  },
  {
    id: 5,
    text: "Meeting ‘Sync with Analese’ set up by Jonathon Johns",
    date: "January 2, 2024 at 14.30PM",
  },
];

export const timeRanges = [
  { startTime: 0, endTime: 2 },
  { startTime: 5, endTime: 6 },
  { startTime: 7, endTime: 9 },
  { startTime: 10, endTime: 30 },
  { startTime: 50, endTime: 70 },
  { startTime: 80, endTime: 100 },
];

export const TimelineData = [
  {
    name: "John Doe",
    email: "john@example.com",
    totalDuration: 100,
    timeRanges: [
      { startTime: 0, endTime: 2 },
      { startTime: 5, endTime: 6 },
      { startTime: 7, endTime: 9 },
      { startTime: 10, endTime: 30 },
      { startTime: 50, endTime: 70 },
    ],
  },
  {
    name: "Jane Smith",
    email: "jane@example.com",
    totalDuration: 80,
    timeRanges: [
      { startTime: 10, endTime: 12 },
      { startTime: 15, endTime: 16 },
      { startTime: 17, endTime: 19 },
      { startTime: 20, endTime: 40 },
      { startTime: 60, endTime: 80 },
    ],
  },
  {
    name: "Alice Johnson",
    email: "alice@example.com",
    totalDuration: 93,
    timeRanges: [
      { startTime: 20, endTime: 22 },
      { startTime: 25, endTime: 26 },
      { startTime: 27, endTime: 29 },
      { startTime: 30, endTime: 50 },
      { startTime: 70, endTime: 90 },
    ],
  },
  {
    name: "Bob Brown",
    email: "bob@example.com",
    totalDuration: 100,
    timeRanges: [
      { startTime: 30, endTime: 32 },
      { startTime: 35, endTime: 36 },
      { startTime: 37, endTime: 39 },
      { startTime: 40, endTime: 60 },
      { startTime: 70, endTime: 100 },
    ],
  },
  {
    name: "Charlie Davis",
    email: "charlie@example.com",
    totalDuration: 150,
    timeRanges: [
      { startTime: 40, endTime: 42 },
      { startTime: 45, endTime: 46 },
      { startTime: 47, endTime: 49 },
      { startTime: 50, endTime: 70 },
      { startTime: 80, endTime: 120 },
    ],
  },
  {
    name: "Diana Prince",
    email: "diana@example.com",
    totalDuration: 100,
    timeRanges: [
      { startTime: 50, endTime: 52 },
      { startTime: 55, endTime: 56 },
      { startTime: 57, endTime: 59 },
      { startTime: 60, endTime: 80 },
      { startTime: 90, endTime: 130 },
    ],
  },
  {
    name: "Ethan Hunt",
    email: "ethan@example.com",
    totalDuration: 150,
    timeRanges: [
      { startTime: 60, endTime: 62 },
      { startTime: 65, endTime: 66 },
      { startTime: 67, endTime: 69 },
      { startTime: 70, endTime: 90 },
      { startTime: 100, endTime: 140 },
    ],
  },
];
export const horizontalChartData = [
   { name: "Muhammadali", averageQuestions: 15 },
   { name: "Sienna", averageQuestions: 20 },
   { name: "Andrew", averageQuestions: 25 }
 ];